package com.jbatrina.BankingApplication.service;

import com.jbatrina.BankingApplication.repository.AccountRepository;
import com.jbatrina.BankingApplication.exceptions.AccountIdConflictException;
import com.jbatrina.BankingApplication.exceptions.AccountNotFoundException;
import com.jbatrina.BankingApplication.entity.Account;
import jakarta.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.Set;

@Service
public class AccountService {
    @Autowired
    AccountRepository accountRepository;
    @Autowired
    RoleService roleService;
    @Autowired
    PasswordEncoder passwordEncoder;

    public Account addAccount(Account account) {
        // NOTE: For requests the body, don't include accountId in body since it is autogenerated
        if (accountRepository.findById(account.getAccountId()).isPresent()) {
            throw new AccountIdConflictException(account.getAccountId()).setContextMessage(
            		"Attempting to add " + account, "::ADD_ACCOUNT_HAS_ID");
        }
        
        accountRepository.save(account);
        return account;
    }

    public Account getById(int accountId) {
        Account account = accountRepository.findById(accountId)
                .orElseThrow(() -> new AccountNotFoundException(accountId).setContextMessage(
                		"No Account with Id " + accountId, "::NONEXISTENT_USER_ID")
                		);

        return account;
    }
}
