package com.jbatrina.BankingApplication.service;

import com.jbatrina.BankingApplication.repository.TransactionRepository;
import com.jbatrina.BankingApplication.repository.TransactionTypeRepository;
import com.jbatrina.BankingApplication.exceptions.TransactionIdConflictException;
import com.jbatrina.BankingApplication.exceptions.TransactionInsufficientBalanceException;
import com.jbatrina.BankingApplication.exceptions.TransactionNotFoundException;
import com.jbatrina.BankingApplication.entity.Account;
import com.jbatrina.BankingApplication.entity.Balance;
import com.jbatrina.BankingApplication.entity.Transaction;
import com.jbatrina.BankingApplication.entity.TransactionType;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
public class TransactionService {
    @Autowired
    TransactionRepository transactionRepository;
    @Autowired
    TransactionTypeRepository accountTypeRepository;

    public Transaction addTransaction(Transaction transaction) {
        // NOTE: For requests the body, don't include transactionId in body since it is autogenerated
        if (transactionRepository.findById(transaction.getTransactionId()).isPresent()) {
            throw new TransactionIdConflictException(transaction.getTransactionId()).setContextMessage(
            		"Attempting to add " + transaction, "::ADD_TRANSACTION_HAS_ID");
        }
        
        transactionRepository.save(transaction);
        return transaction;
    }

    public Transaction getById(int transactionId) {
        Transaction transaction = transactionRepository.findById(transactionId)
                .orElseThrow(() -> new TransactionNotFoundException(transactionId).setContextMessage(
                		"No Transaction with Id " + transactionId, "::NONEXISTENT_TRANSACTION_ID")
                		);

        return transaction;
    }
    
    
    // NOTE: currently used for query transactions (e.g. check balance)
    public Transaction addSelfTransaction(
		Account account, 
		TransactionType transactionType
	) {
    	return addTransaction(new Transaction(account, account, transactionType, Balance.ofBase(0)));
    }

    public Transaction closeTransaction(Transaction transaction) {
    	transaction.setClosureTimeStamp(LocalDateTime.now());
 
    	return transaction;
    }
    
    	
    public Transaction createFundTransfer(Transaction transaction) {
    	Account sourceAccount = transaction.getSourceAccount();
    	Account targetAccount = transaction.getTargetAccount();

    	if (! sourceAccount.hasBalance(transaction.getAffectedBalance())) {
			throw new TransactionInsufficientBalanceException(transaction.getTransactionId())
				.setTransaction(transaction)
				.setContextMessage(
						String.format("Account %s has inssuficient balance for this transfer", sourceAccount),
						"::TRANSACTION_INSUFFICIENT_BALANCE"
					);
    	}
    	
    	return addTransaction(transaction);
    }
}
