package com.jbatrina.BankingApplication.service;

import com.jbatrina.BankingApplication.repository.AccountRepository;
import com.jbatrina.BankingApplication.repository.TransactionRepository;
import com.jbatrina.BankingApplication.repository.TransactionTypeRepository;
import com.jbatrina.BankingApplication.exceptions.TransactionException;
import com.jbatrina.BankingApplication.exceptions.TransactionIdConflictException;
import com.jbatrina.BankingApplication.exceptions.TransactionNotFoundException;
import com.jbatrina.BankingApplication.entity.Account;
import com.jbatrina.BankingApplication.entity.Balance;
import com.jbatrina.BankingApplication.dto.BalanceDto;
import com.jbatrina.BankingApplication.dto.TransactionDto;
import com.jbatrina.BankingApplication.entity.Transaction;
import com.jbatrina.BankingApplication.entity.TransactionType;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
public class TransactionService {
    @Autowired
    TransactionRepository transactionRepository;
    @Autowired
    TransactionTypeRepository transactionTypeRepository;
    @Autowired
    AccountRepository accountRepository;
    @Autowired
    AccountService accountService;

    public Transaction addTransaction(Transaction transaction) {
        // NOTE: For requests the body, don't include transactionId in body since it is autogenerated
        if (transactionRepository.findById(transaction.getTransactionId()).isPresent()) {
            throw new TransactionIdConflictException(transaction.getTransactionId()).setContextMessage(
            		"Supplied transaction must not contain an Id (will be autogenerated)", "::ADD_TRANSACTION_HAS_ID");
        }
        
        transactionRepository.save(transaction);
        return transaction;
    }

    public Transaction getTransaction(int transactionId) {
        Transaction transaction = transactionRepository.findById(transactionId)
                .orElseThrow(() -> new TransactionNotFoundException(transactionId).setContextMessage(
                		"No Transaction with Id " + transactionId, "::NONEXISTENT_TRANSACTION_ID")
                		);

        return transaction;
    }
    
	public Page<Transaction> getAllTransactionsOfAccountByPage(int accountId, int pageNo, int pageSize) {
    	// on the caller side, we set pageNo to be 1-indexed
    	// but PageRequest is 0-indexed, so we just subtract by one
    	// and set the minimum page to 1
    	--pageNo;
    	pageNo = Math.max(0, pageNo);

    	Pageable pageable;
    	if (pageSize > 0) {
			pageable = PageRequest.of(pageNo, pageSize);
    	} else {
			pageable = Pageable.unpaged();
    	}

        return transactionRepository.findAllBySourceAccountAccountIdOrTargetAccountAccountId(accountId, accountId, pageable);
	}
    
    public Transaction closeTransaction(Transaction transaction) {
        // NOTE: For now, transactions are closed the same time they are created so closeTransaction
    	//       essentially acts as addTransaction. Hence, we also want to check for id in request
        if (transactionRepository.findById(transaction.getTransactionId()).isPresent()) {
            throw new TransactionIdConflictException(transaction.getTransactionId()).setContextMessage(
            		"Supplied transaction must not contain an Id (will be autogenerated)", "::CLOSE_TRANSACTION_HAS_ID");
        }

    	transaction.setClosureTimeStamp(LocalDateTime.now());
 
        transactionRepository.save(transaction);

        // save changes to accounts
        accountRepository.save(transaction.getSourceAccount());
        accountRepository.save(transaction.getTargetAccount());

    	return transaction;
    }
    
    	
    public Transaction createFundTransfer(TransactionDto transactionDto) {
    	return createFundTransfer(fromTransactionDto(transactionDto));
    }

    public Transaction createFundTransfer(Transaction transaction) {
    	Account sourceAccount = transaction.getSourceAccount();
    	Account targetAccount = transaction.getTargetAccount();
 
    	// TODO: use TransactionTypeService to get this fund transfer type
    	TransactionType fundTransferTransaction = transactionTypeRepository.findByName("FUND_TRANSFER")
    			.orElseThrow(() -> new TransactionException(transaction.getTransactionId())
								.setContextMessage(
										"Fund transfer transaction type not initialized",
										"::FUND_TRANSFER_NOINIT"
									)
					);
    	
    	// normalize transaction: set balance to positive values (transfers always from SOURCE to TARGET)
    	transaction.setAffectedBalance(transaction.getAffectedBalance().getAbsoluteValue());

    	if (transaction.getTransactionType().equals(fundTransferTransaction)) {
			throw new TransactionException(transaction.getTransactionId())
				.setTransaction(transaction)
				.setContextMessage(
						String.format("Fund transfer transactions must have correct type (%d but expected %d)",
								transaction.getTransactionType().getTypeId(), fundTransferTransaction.getTypeId()
							),
						"::TRANSACTION_FUND_TRANSFER_WRONGTYPE"
					);
    	}

    	
		// addTransaction(transaction);
    	sourceAccount.withdraw(transaction.getAffectedBalance());
    	targetAccount.deposit(transaction.getAffectedBalance());

    	// TODO: maybe some other processing steps before closing?
    	closeTransaction(transaction);
    	
    	return transaction;
    }
    
    public Transaction createBalanceCheck(Account account) {
    	// TODO: use TransactionTypeService to get this fund transfer type
    	TransactionType balanceCheckTransaction = transactionTypeRepository.findByName("BALANCE_CHECK")
    			.orElseThrow(() -> new TransactionException(-1)
								.setContextMessage(
										"Balance check transaction type not initialized",
										"::BALANCE_CHECK_NOINIT"
									)
					);
    	
      	// addSelfTransaction(account, balanceCheckTransaction);
    	Transaction t = new Transaction(account, account, balanceCheckTransaction, Balance.ofBase(0));
		closeTransaction(t);
		
		return t;
    }

    public TransactionDto makeTransactionDto(Transaction transaction) {
    	return new TransactionDto(
    			transaction.getTransactionId(),
    			transaction.getTransactionType(),
    			transaction.getSourceAccount().getAccountId(),
    			transaction.getTargetAccount().getAccountId(),
    			BalanceDto.of(transaction.getAffectedBalance()),
    			transaction.getCreationTimeStamp(),
    			transaction.getClosureTimeStamp()
			);
    }
    
    public Transaction fromTransactionDto(TransactionDto transactionDto) {
		return new Transaction(
				transactionDto.getTransactionId(),
				transactionDto.getTransactionType(),
				accountService.getAccount(transactionDto.getSourceAccountId()),
				accountService.getAccount(transactionDto.getTargetAccountId()),
				transactionDto.getAffectedBalance().toBalance(),
				transactionDto.getCreationTimeStamp(),
				transactionDto.getClosureTimeStamp()
			);
    }
}
