package com.jbatrina.BankingApplication.service;

import com.jbatrina.BankingApplication.repository.AccountRepository;
import com.jbatrina.BankingApplication.repository.TransactionRepository;
import com.jbatrina.BankingApplication.repository.TransactionTypeRepository;
import com.jbatrina.BankingApplication.exceptions.TransactionException;
import com.jbatrina.BankingApplication.exceptions.TransactionIdConflictException;
import com.jbatrina.BankingApplication.exceptions.TransactionInsufficientBalanceException;
import com.jbatrina.BankingApplication.exceptions.TransactionNotFoundException;
import com.jbatrina.BankingApplication.entity.Account;
import com.jbatrina.BankingApplication.entity.Balance;
import com.jbatrina.BankingApplication.dto.BalanceDto;
import com.jbatrina.BankingApplication.entity.Transaction;
import com.jbatrina.BankingApplication.entity.TransactionType;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
public class TransactionService {
    @Autowired
    TransactionRepository transactionRepository;
    @Autowired
    TransactionTypeRepository transactionTypeRepository;
    @Autowired
    AccountRepository accountRepository;

    public Transaction addTransaction(Transaction transaction) {
        // NOTE: For requests the body, don't include transactionId in body since it is autogenerated
        if (transactionRepository.findById(transaction.getTransactionId()).isPresent()) {
            throw new TransactionIdConflictException(transaction.getTransactionId()).setContextMessage(
            		"Attempting to add " + transaction, "::ADD_TRANSACTION_HAS_ID");
        }
        
        transactionRepository.save(transaction);
        return transaction;
    }

    public Transaction getById(int transactionId) {
        Transaction transaction = transactionRepository.findById(transactionId)
                .orElseThrow(() -> new TransactionNotFoundException(transactionId).setContextMessage(
                		"No Transaction with Id " + transactionId, "::NONEXISTENT_TRANSACTION_ID")
                		);

        return transaction;
    }
    
    public Transaction closeTransaction(Transaction transaction) {
    	transaction.setClosureTimeStamp(LocalDateTime.now());
 
        transactionRepository.save(transaction);

        // save changes to accounts
        accountRepository.save(transaction.getSourceAccount());
        accountRepository.save(transaction.getTargetAccount());

    	return transaction;
    }
    
    	
    public Transaction createFundTransfer(Transaction transaction) {
    	Account sourceAccount = transaction.getSourceAccount();
    	Account targetAccount = transaction.getTargetAccount();
 
    	// TODO: use TransactionTypeService to get this fund transfer type
    	TransactionType fundTransferTransaction = transactionTypeRepository.findByName("FUND_TRANSFER")
    			.orElseThrow(() -> new TransactionException(transaction.getTransactionId())
								.setContextMessage(
										"Fund transfer transaction type not initialized",
										"::FUND_TRANSFER_NOINIT"
									)
					);
    	
    	// normalize transaction: set balance to positive values (transfers always from SOURCE to TARGET)
    	transaction.setAffectedBalance(transaction.getAffectedBalance().getAbsoluteValue());

    	if (transaction.getTransactionType().equals(fundTransferTransaction)) {
			throw new TransactionException(transaction.getTransactionId())
				.setTransaction(transaction)
				.setContextMessage(
						String.format("Fund transfer transactions must have correct type (%d but expected %d)",
								transaction.getTransactionType().getTypeId(), fundTransferTransaction.getTypeId()
							),
						"::TRANSACTION_FUND_TRANSFER_WRONGTYPE"
					);
    	}

    	
		// addTransaction(transaction);
    	sourceAccount.withdraw(transaction.getAffectedBalance());
    	targetAccount.deposit(transaction.getAffectedBalance());

    	// TODO: maybe some other processing steps before closing?
    	closeTransaction(transaction);
    	
    	return transaction;
    }
    
    public Transaction createBalanceCheck(Account account) {
    	// TODO: use TransactionTypeService to get this fund transfer type
    	TransactionType balanceCheckTransaction = transactionTypeRepository.findByName("FUND_TRANSFER")
    			.orElseThrow(() -> new TransactionException(-1)
								.setContextMessage(
										"Balance check transaction type not initialized",
										"::BALANCE_CHECK_NOINIT"
									)
					);
    	
      	// addSelfTransaction(account, balanceCheckTransaction);
    	Transaction t = new Transaction(account, account, balanceCheckTransaction, Balance.ofBase(0));
		closeTransaction(t);
		
		return t;
    }
}
