spring:
  config:
    import: "optional:configserver:"
  devtools:
    restart:
      enabled: false
  cloud:
    gateway:
      mvc:
        routes:
          # Authentication
          - id: login
            uri: http://localhost:8080
            filters:
              - SetPath=/api/auth/login
            predicates:
              - Path=/login
          - id: signup
            uri: http://localhost:8080
            filters:
              - SetPath=/api/auth/signup
            predicates:
              - Path=/signup
          # Department
          - id: dept_get_all
            uri: http://localhost:8080
            filters:
              - SetPath=/api/departments
            predicates:
              - Path=/allDepts
          - id: dept_get
            uri: http://localhost:8080
            filters:
              - RewritePath=/getDept/(?<segment>.*), /api/department/${segment}
            predicates:
              - Path=/getDept/**
          - id: dept_add
            uri: http://localhost:8080
            filters:
              - SetPath=/api/addDepartment
            predicates:
              - Path=/addDept
          - id: dept_update
            uri: http://localhost:8080
            filters:
              - RewritePath=/editDept/(?<segment>.*), /api/updateDepartment/${segment}
            predicates:
              - Path=/editDept/**
          - id: dept_remove
            uri: http://localhost:8080
            filters:
              - RewritePath=/delDept/(?<segment>.*), /api/removeDepartment/${segment}
            predicates:
              - Path=/delDept/**
          - id: dept_add_employeees
            uri: http://localhost:8080
            filters:
              - RewritePath=/addDeptEmployees/(?<segment>.*), /api/addDepartmentEmployees/${segment}
            predicates:
              - Path=/addDeptEmployees/**
          - id: dept_remove_employeees
            uri: http://localhost:8080
            filters:
              - RewritePath=/delDeptEmployees/(?<segment>.*), /api/removeDepartmentEmployees/${segment}
            predicates:
              - Path=/delDeptEmployees/**
          # Employees
          - id: employee_get_all
            uri: http://localhost:8080
            filters:
              - SetPath=/api/employees
            predicates:
              - Path=/getAllEmployees
          - id: employee_get
            uri: http://localhost:8080
            filters:
              - RewritePath=/getEmployee/(?<segment>.*), /api/employee/${segment}
            predicates:
              - Path=/getEmployee/**
          - id: employee_add
            uri: http://localhost:8080
            filters:
              - SetPath=/api/addEmployee
            predicates:
              - Path=/addEmployee
          - id: employee_update
            uri: http://localhost:8080
            filters:
              - RewritePath=/editEmployee/(?<segment>.*), /api/updateEmployee/${segment}
            predicates:
              - Path=/editEmployee/**
          - id: employee_remove
            uri: http://localhost:8080
            filters:
              - RewritePath=/delEmployee/(?<segment>.*), /api/removeEmployee/${segment}
            predicates:
              - Path=/delEmployee/**
          - id: employee_remove_multiple
            uri: http://localhost:8080
            filters:
              - SetPath=/api/removeEmployees
            predicates:
              - Path=/delEmployees
          - id: employee_get_avg_salary
            uri: http://localhost:8080
            filters:
              - SetPath=/api/getAverageSalary
            predicates:
              - Path=/getAvgSalary
          - id: employee_get_avg_age
            uri: http://localhost:8080
            filters:
              - SetPath=/api/getAverageAge
            predicates:
              - Path=/getAvgAge
management:
  endpoints:
    web:
      exposure:
        include: refresh
  endpoint:
      refresh:
        enabled: true
