spring:
  config:
    import: "optional:configserver:"
  devtools:
    restart:
      enabled: false
  cloud:
    gateway:
      mvc:
        routes:
          # Authentication
          - id: login
            uri: http://localhost:8080
            filters:
              - SetPath=/api/auth/login
            predicates:
              - Path=/login
          - id: signup
            uri: http://localhost:8080
            filters:
              - SetPath=/api/auth/signup
            predicates:
              - Path=/signup
management:
  endpoints:
    web:
      exposure:
        include: refresh
  endpoint:
      refresh:
        enabled: true
